services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    restart: always
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
kibana:
    image: docker.elastic.co/kibana/kibana:9.4.2
    restart: always
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  logstash:
    image: docker.elastic.co/logstash/logstash:9.4.2
    restart: always
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/conf.d:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    environment:
      - LS_JAVA_OPTS=-Xms4g -Xmx4g
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
