filter {
  if [winlog][channel] == "Application" {

    ##########################################################################
    # EVENT CATEGORY VE TAGLAR
    ##########################################################################
    mutate {
      add_field => { "[event][category]" => "application" }
      add_tag => ["dc", "application"]
    }

    # 1000 - Application Error
    if [event][code] == "1000" {
      mutate {
        add_field => { "[event][subcategory]" => "application_error" }
        add_tag => ["app_crash"]
      }
    }

    # 1001 - Windows Error Reporting
    if [event][code] == "1001" {
      mutate {
        add_tag => ["wer_report"]
      }
    }
  }
}