filter {
  if [winlog][channel] == "System" {

    ##########################################################################
    # EVENT CATEGORY VE TAGLAR
    ##########################################################################
    mutate {
      add_field => { "[event][category]" => "system" }
      add_tag => ["dc", "system"]
    }

    # 6005 - Event Log Service Started
    if [event][code] == "6005" {
      mutate { add_tag => ["system_start"] }
    }

    # 6006 - Event Log Service Stopped
    if [event][code] == "6006" {
      mutate { add_tag => ["system_stop"] }
    }

    # 41 - Unexpected Shutdown
    if [event][code] == "41" {
      mutate { add_tag => ["unexpected_shutdown", "critical_error"] }
    }
  }
}