filter {
  if "messagetracking" in [tags] {
    csv {
      separator => ","
      skip_header => true
      columns => [
        "date-time", "client-ip", "client-hostname", "server-ip", "server-hostname",
        "source-context", "connector-id", "source", "event-id", "internal-message-id",
        "message-id", "network-message-id", "recipient-address", "recipient-status",
        "total-bytes", "recipient-count", "related-recipient-address", "reference",
        "message-subject", "sender-address", "return-path", "message-info",
        "directionality", "tenant-id", "original-client-ip", "original-server-ip",
        "custom-data", "transport-traffic-type", "log-id", "schema-version"
      ]
    }

    date {
      match => ["date-time", "ISO8601"]
      target => "@timestamp"
      timezone => "Europe/Istanbul"
    }

    mutate {
      add_field => { "log_type" => "messagetracking" }
    }

    # Eğer recipient-address birden fazlaysa, ayırmak için:
    if [recipient-address] =~ ";" {
      mutate {
        split => { "recipient-address" => ";" }
      }
      split {
        field => "recipient-address"
      }
    }
  }
}
