output {

  ## Exchange Message Tracking
  if "messagetracking" in [tags] {
    stdout { codec => rubydebug }
    elasticsearch {
      hosts => ["http://172.22.22.171:9200"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      index => "exchange-messagetracking-%{+YYYY.MM.dd}"
    }
  }

  ## DC Application
  if "application" in [tags] {
    stdout { codec => rubydebug }
    elasticsearch {
      hosts => ["http://172.22.22.171:9200"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      index => "dc-application-%{+YYYY.MM.dd}"
    }
  }

  #######################################################################
  ## DC SECURITY ROUTINE — ÖNCE
  #######################################################################
  if "security-routine" in [tags] {
    stdout { codec => rubydebug }
    elasticsearch {
      hosts => ["http://172.22.22.171:9200"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      index => "dc-security-routine-%{+YYYY.MM.dd}"
    }
  }

  #######################################################################
  ## DC SECURITY — SADECE routine OLMAYANLAR
  #######################################################################
  if "security" in [tags] and "security-routine" not in [tags] {
    stdout { codec => rubydebug }
    elasticsearch {
      hosts => ["http://172.22.22.171:9200"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      index => "dc-security-%{+YYYY.MM.dd}"
    }
  }

  ## DC System
  if "system" in [tags] {
    stdout { codec => rubydebug }
    elasticsearch {
      hosts => ["http://172.22.22.171:9200"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      index => "dc-system-%{+YYYY.MM.dd}"
    }
  }

}