input {
  beats {
    port => 5044
  }
}

filter {
  if "iis" in [tags] {
    # CSV parser
    csv {
      separator => " "
      skip_empty_columns => true
      columns => [
        "date", "time", "s-sitename", "s-computername", "s-ip",
        "cs-method", "cs-uri-stem", "cs-uri-query", "s-port",
        "cs-username", "c-ip", "cs-version", "cs(User-Agent)",
        "cs(Cookie)", "cs(Referer)", "cs-host", "sc-status",
        "sc-substatus", "sc-win32-status", "sc-bytes", "cs-bytes",
        "time-taken", "x-forwarded-for"
      ]
    }

    # date + time birleştirip @timestamp yapalım
    mutate {
      add_field => { "log_timestamp" => "%{date} %{time}" }
      add_field => { "log_type" => "iis" }
    }

    date {
      match => ["log_timestamp", "YYYY-MM-dd HH:mm:ss"]
      target => "@timestamp"
      timezone => "UTC"
    }

    mutate {
      remove_field => ["date", "time", "log_timestamp"]
    }
  }
}

output {
  if "iis" in [tags] {
    stdout { codec => rubydebug }

    elasticsearch {
      hosts => ["http://172.22.22.171:9200"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      index => "iis-logs-%{+YYYY.MM.dd}"
    }
  }
}
